{
    "package":"package",
    "AndroidManifest":["AndroidManifest"],
    "activity":["H1","H2","H3"],
    "rules":{
        "activity":{
            "指定模板文件的名字":["Activity.java","activity.xml"]
        },
        "AndroidManifest":{
            "指定模板文件的名字":["AndroidManifest.txt"]
        }
    }
}
